spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baseball_db
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
  jwt:
    secret: test!@#$